### ISSUE TITLE
ENH: Create a conda package

### ISSUE THREAD

**Issue by remi-braun** [youknowone/methodtools#15]
Hello,

First of all, nice lib that solved some troubles 😄 

However, could you create a conda package in order to allow other packages to use methodtools through conda ? (via [conda forge](https://conda-forge.org/) for example)

Thanks a lot !

**Comment by youknowone** [comment]
Hello,

I thought pypi packaging is enough for python packages.

I never used conda myself, so I don't know well about them. Is there any problem to use pypi package from conda environment?

**Comment by remi-braun** [comment]
The problem is that you cannot create a conda package that includes methodtools by default.

And it is not recommended to mix installing libs via conda and pip, it should be either one or the other

**Comment by remi-braun** [comment]
Just to precise what I meant, here is a thread where it is specified you cannot create a conda package with pip-only dependencies:
https://github.com/conda/conda-build/issues/548#issuecomment-780851036 

You can, however, create a conda environment mixing the to packaging ways, but this is not really user-friendly 😄

**Comment by rdgraham** [comment]
Just wondering if there is any progress on this. Looks like a good tool but without a conda package I will need to find another solution.

**Comment by youknowone** [comment]
Thanks all. I now understand the situation.

After reseraching how to manage conda package, I found it does not necessarily need to be managed by myself - it didn't have ownerships for packages but anyone can submit recipes. Because I didn't use conda for myself ever, I don't think I can manage the conda recipes for this package well.

Instead, I am opened to anyone who will create conda package for this project. And I will do my best support for anyone who will do it, but I will not create and manage recipes myself. Please contact me anyone needs any help for that.

**Comment by remi-braun** [comment]
If I'm not mistaken, your lib is using another package of yours called `wirerope` which doesn't have a conda package either.
If so, the package should also be created for it.
Is there any other dependency behind this one ?

**Comment by youknowone** [comment]
You are right. `methodtools` is very small, single file library wrapping `wirerope`. It only has one dependency.

`wirerope` depends on a few compatibility tools. `six` is very common, so it will not be a problem. To support Python2, it additionally requires `inspect2` and `singledispatch`. 
https://github.com/youknowone/wirerope/blob/master/setup.cfg

**Comment by timkpaine** [comment]
im doing it here: https://github.com/conda-forge/staged-recipes/pull/18907

**Comment by remi-braun** [comment]
> im doing it here: [conda-forge/staged-recipes#18907](https://github.com/conda-forge/staged-recipes/pull/18907)

Real heroes don't wear capes!
I can take it away from my personal todolist thanks to you 🙏

**Comment by timkpaine** [comment]
This issue can be closed now https://anaconda.org/conda-forge/methodtools

**Comment by youknowone** [comment]
Thank you! this is great!
